#!/bin/sh
# Generates src/version.ts with semver + short commit hash.
# Called by build script.
set -e

VERSION=$(node -p "require('./package.json').version")
HASH=$(git rev-parse --short HEAD 2>/dev/null || echo "dev")

cat > src/version.ts <<EOF
// Auto-generated by scripts/gen-version.sh — do not edit
export const VERSION = "${VERSION}+${HASH}";
EOF

echo "Generated src/version.ts: ${VERSION}+${HASH}"
